const CONNECT = 'CONNECT'
const DISCONNECT = 'DISCONNECT'
const NEW_TASK = 'NEW_TASK'
const UPDATE_TASK = 'UPDATE_TASK'
const PAUSE_TASK = 'PAUSE_TASK'
const START_TASK = 'START_TASK'
const STOP_TASK = 'STOP_TASK'
const COMPLETE_TASK = 'COMPLETE_TASK'
const EVALUATE = 'EVALUATE'
const EVALUATED = 'EVALUATED'

module.exports = {
  CONNECT,
  DISCONNECT,
  NEW_TASK,
  UPDATE_TASK,
  PAUSE_TASK,
  START_TASK,
  STOP_TASK,
  COMPLETE_TASK,
  EVALUATE,
  EVALUATED,
}
