const CONNECT = 'CONNECT'
const DISCONNECT = 'DISCONNECT'
const IMPORT_TASKS = 'IMPORT_TASKS'
const NEW_TASK = 'NEW_TASK'
const UPDATE_TASK = 'UPDATE_TASK'
const PAUSE_TASK = 'PAUSE_TASK'
const START_TASK = 'START_TASK'
const STOP_TASK = 'STOP_TASK'
const COMPLETE_TASK = 'COMPLETE_TASK'
const RENAME_TASK = 'RENAME_TASK'
const ARCHIVE_TASK = 'ARCHIVE_TASK'
const UNARCHIVE_TASK = 'UNARCHIVE_TASK'
const DELETE_TASK = 'DELETE_TASK'
const UPDATE_TASK_DESCR = 'UPDATE_TASK_DESCR'
const EVALUATE = 'EVALUATE'
const EVALUATED = 'EVALUATED'
const RENAME_CLIENT = 'RENAME_CLIENT'
const OBSERVE_TASK = 'OBSERVE_TASK'
const UPDATE_CLIENT_DESCR = 'UPDATE_CLIENT_DESCR'

module.exports = {
  CONNECT,
  DISCONNECT,
  IMPORT_TASKS,
  NEW_TASK,
  UPDATE_TASK,
  PAUSE_TASK,
  START_TASK,
  STOP_TASK,
  COMPLETE_TASK,
  RENAME_TASK,
  ARCHIVE_TASK,
  UNARCHIVE_TASK,
  DELETE_TASK,
  UPDATE_TASK_DESCR,
  EVALUATE,
  EVALUATED,
  RENAME_CLIENT,
  OBSERVE_TASK,
  UPDATE_CLIENT_DESCR,
}
