const CONNECT = 'CONNECT'
const DISCONNECT = 'DISCONNECT'
const NEW_TASK = 'NEW_TASK'
const UPDATE_TASK = 'UPDATE_TASK'
const PAUSE_TASK = 'PAUSE_TASK'
const START_TASK = 'START_TASK'
const STOP_TASK = 'STOP_TASK'
const COMPLETE_TASK = 'COMPLETE_TASK'
const RENAME_TASK = 'RENAME_TASK'
const ARCHIVE_TASK = 'ARCHIVE_TASK'
const UNARCHIVE_TASK = 'UNARCHIVE_TASK'
const DELETE_TASK = 'DELETE_TASK'
const EVALUATE = 'EVALUATE'
const EVALUATED = 'EVALUATED'
const RENAME_CLIENT = 'RENAME_CLIENT'

module.exports = {
  CONNECT,
  DISCONNECT,
  NEW_TASK,
  UPDATE_TASK,
  PAUSE_TASK,
  START_TASK,
  STOP_TASK,
  COMPLETE_TASK,
  RENAME_TASK,
  ARCHIVE_TASK,
  UNARCHIVE_TASK,
  DELETE_TASK,
  EVALUATE,
  EVALUATED,
  RENAME_CLIENT,
}
